### ISSUE TITLE
Create basic HTML page with CSS

### ISSUE THREAD

**Issue by zetslief** [zetslief/flowers#2]
# Create basic HTML page with CSS

1. Create `index.html` page with the single tag in the body: `<p>Hello, Web!</p>`
2. Create `styles.css` file that makes `background-color` green for all `<p>` tags.
3. Add link to `styles.css` to the `index.html`.

# Expected result
Basic HTML page with `Hello,Web!` text on `green` background.

**Comment by GabrielCoutz** [comment]
Hi @zetslief, i think that these codes is what u need, right?

## index.html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <p>Hello, Web!</p>
</body>
</html>
```
## styles.css
```css
* {
  background-color: green;
}
```

**Comment by zetslief** [comment]
Correct 😁
